### ISSUE TITLE
Emojis not showing in staging env

### ISSUE THREAD

**Issue by tbilous** [ID25/rails_emoji_picker#25]
I was added new environment "staging" for my staging deploy
Under this env emji rendered like  this: 
<span class="emoji-image"><img alt="kiss" class="emoji" src="💋"></span>

**Comment by jaimearroyonavia** [comment]
I have the same issue and i make a fork of this repository whit a fix for that: https://github.com/kensk8/rails_emoji_picker  

Here is why on other environment this happen https://github.com/kensk8/rails_emoji_picker/commit/9c6de562f4f0790e03956f10ec64e95fddefbb53

**Comment by aynul** [comment]
Also had broken images until using @kensk8's version, thanks!

**Comment by RailsCod3rFuture** [comment]
@kensk8 Hey Ken - I'm unable to retrieve assets with your fork of rails_emoji_picker with Rails 5.2. Do you know what the problem may be when I see the error below??

http://imgur.com/3jQxLjR



```

 C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/exception_handler-0.8.0.0/lib/exception_handler/engine.rb:54:in `block (2 levels) in <class:Engine>'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:38:in `call_app'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `block in call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/logger_silence.rb:21:in `silence'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/logger.rb:65:in `block (3 levels) in broadcast'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/logger_silence.rb:21:in `silence'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/logger.rb:63:in `block (2 levels) in broadcast'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/static.rb:127:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
  
  
  
ActionController::RoutingError (No route matches [GET] "/assets/packs/basic/3,2,27,:us:"):
  
ActionController::RoutingError (No route matches [GET] "/assets/packs/basic/3,2,28,:fr:"):
ActionController::RoutingError (No route matches [GET] "/assets/packs/basic/3,2,30,:it:"):
  
ActionController::RoutingError (No route matches [GET] "/assets/packs/basic/3,2,29,:es:"):
  
  
  
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
```
