### ISSUE TITLE
binread Errno::ENOENT

### ISSUE THREAD

**Issue by dcalixto** [ID25/rails_emoji_picker#7]
Hi, after run the install generator show up this message. may i have to update thor?
```
    
insert  app/assets/javascripts/application.js
      insert  app/assets/stylesheets/application.css
      insert  config/initializers/assets.rb
/Users/daniel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/daniel/jetzx/config/initializers/assets.rb (Errno::ENOENT)
from /Users/daniel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
	from /Users/daniel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
	from /Users/daniel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/daniel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
	from /Users/daniel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails_emoji_picker-0.1.0/lib/generators/rails_emoji_picker/install_generator.rb:26:in `insert_to_assets'

```

**Comment by ID25** [comment]
Are you using rails 3?
This is your error:
``No such file or directory @ rb_sysopen - /Users/daniel/jetzx/config/initializers/assets.rb``
I'm too busy now, i'll fix it in later. Try to add these lines to your ``application.rb``
```ruby
Rails.application.config.assets.paths << Emoji.images_path
Rails.application.config.assets.precompile += %w(emoji/*.png)
```

**Comment by dcalixto** [comment]
yes, i'm using. right. thank you very much @ID25
